# Generated by Django 3.0.6 on 2020-05-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
